// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdhbavpfwyymzxrxlhjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkaGJhdnBmd3l5bXp4cnhsaGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxODIwNTcsImV4cCI6MjA2Nzc1ODA1N30.c4u2LA0ixabxSbFPmzDua8ZxRz9i6Sbn-z2U4SoWCNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});